server:
  port: ${PORT:9006}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL}/master-data
  application:
    name: MASTER-DATA-SERVICE

app:
  utils:
    auth-service-base-url: ${AUTH_SERVICE_BASE_URL}
    internal-access-token: ${INTERNAL_ACCESS_TOKEN}

